### ISSUE TITLE
"--ignore func" requires a func folder still

### ISSUE THREAD

**Issue by ericearl** [DCAN-Labs/abcd-hcp-pipeline#1]
A subject that looks like this:

```
sub-ANATONLY/
|__ ses-baselineYear1Arm1
    |__ anat
        |__ sub-ANATONLY_ses-baselineYear1Arm1_rec-normalized_T1w.json
        |__ sub-ANATONLY_ses-baselineYear1Arm1_rec-normalized_T1w.nii.gz
        |__ sub-ANATONLY_ses-baselineYear1Arm1_rec-normalized_T2w.json
        |__ sub-ANATONLY_ses-baselineYear1Arm1_rec-normalized_T2w.nii.gz
```

Is not accepted with the `--ignore func` option in place because of this error:

```
user@server:/projects/ABCD/docker_pull_test$ docker run --rm -v /projects/ABCD/docker_pull_test/input:/input:ro -v /projects/ABCD/docker_pull_test/output:/output -v /software/freesurfer/LICENSE:/license:ro -v /projects/ABCD/docker_pull_test/ABCD_BIDS_cleaning.json:/cleaning.json:ro dcanlabs/abcd-hcp-pipeline /input /output --participant-label ANATONLY --freesurfer-license /license --ncpus 6 --custom-clean /cleaning.json --print-commands-only --ignore func
/usr/local/lib/python3.6/dist-packages/bids/layout/bids_layout.py:116: UserWarning: 'dataset_description.json' file is missing from project root. You may want to set the root path to a valid BIDS project.
  warnings.warn("'dataset_description.json' file is missing from "
Traceback (most recent call last):
  File "/app/run.py", line 304, in <module>
    _cli()
  File "/app/run.py", line 65, in _cli
    return interface(**kwargs)
  File "/app/run.py", line 216, in interface
    for session in session_generator:
  File "/app/helpers.py", line 65, in read_bids_dataset
    func = set_functionals(layout, subject, sessions)
  File "/app/helpers.py", line 119, in set_functionals
    'func_metadata': func_metadata[0]
IndexError: list index out of range
```

Though the exact same arguments given to a subject with `anat` and `func` folders under their BIDS input folder does not have this problem.

Also, it does not ignore additional functional arguments like `--bandstop` or `--abcd-task`.

**Comment by dasturge** [comment]
develop: no longer crashes during setup, however crashes at Executive Summary when no func folder exists.

**Comment by ericearl** [comment]
The actual ExecutiveSummary error is that the `func` folder is being passed as the `unproc_root` to the `executivesummary_wrapper.sh`.  Passing the `anat` folder every time instead would fix this.

```
executivesummary_wrapper.sh  --unproc_root '/input/sub-ANATONLY/ses-baselineYear1Arm1/func' --deriv_root '/output/sub-ANATONLY/ses-baselineYear1Arm1/files' --subject_id 'ANATONLY' --ex_summ_dir 'summary_DCANBOLDProc_v4.0.0' --

COMMAND LINE ARGUMENTS:
unproc_root=/input/sub-ANATONLY/ses-baselineYear1Arm1/func
deriv_root=/output/sub-ANATONLY/ses-baselineYear1Arm1/files
subject_id=ANATONLY
ex_summ_dir=summary_DCANBOLDProc_v4.0.0
End of args

ProcessedFiles=/output/sub-ANATONLY/ses-baselineYear1Arm1/files
Usage: executivesummary_wrapper.sh [options...] 
      Assumes BIDS & DCAN file structure, as follows:
           <unproc_root>/sub-<subject_id>/ses-<visit>/func
           <deriv_root>/sub-<subject_id>/ses-<visit>/files/<ex_summ_dir>
 
      Required:
      -u|--unproc_root        Path to unprocessed data set, ending 'func' or 'anat' or whatever.
      -d|--deriv_root         Path to derivatives files, ending at files. 
      -s|--subject_id         Subject ID without sub- prefix
      -e|--ex_summ_dir        Executive summary subdirectory, for example: summary_DCANBOLDProc_v4.0.0 
 
      Optional:
      -o|--output_path        Path to a writable directory where a copy of the output will be placed 
      -a|--atlas              atlas file for generation of rest image. Overrides MNI 1mm atlas
      -h|--help               Display this message
```
