### ISSUE TITLE
Error Reporting: No BIDS input

### ISSUE THREAD

**Issue by dasturge** [DCAN-Labs/abcd-hcp-pipeline#10]
The pipeline throws an unhelpful python index error when the input BIDS dataset is not found, we should develop good error reporting for basic possible missing files from the input structure, or when no input BIDS is identified at all.

**Comment by dasturge** [comment]
example:

```
Traceback (most recent call last):
  File "/app/run.py", line 364, in <module>
    _cli()
  File "/app/run.py", line 66, in _cli
    return interface(**kwargs)
  File "/app/run.py", line 260, in interface
    for session in session_generator:
  File "/app/helpers.py", line 64, in read_bids_dataset
    anat = set_anatomicals(layout, subject, sessions)
  File "/app/helpers.py", line 84, in set_anatomicals
    t1w_metadata = layout.get_metadata(t1ws[0].filename)
IndexError: list index out of range
```

**Comment by tikal004** [comment]
Old issue, someone has already made a fix for this.
