### ISSUE TITLE
KeyError: 'PixelBandwidth'

### ISSUE THREAD

**Issue by JD-Hwang** [DCAN-Labs/abcd-hcp-pipeline#119]
### What happened?

I tried running ABCD-HCP-pipeline docker with some of the 2-year follow-up ABCD bids data to get the RSFC matrix but got a KeyError of t1w metadata.
I guess all other arguments were well given... what should I do? Has anyone had a similar issue? 

![image](https://github.com/user-attachments/assets/09d4113d-d5d6-441f-b47d-2ab0325971ab)

### What command did you use?

```shell
sudo docker run -v /data5/open_data/ABCD/4.0/Package_1204192/fmriresults01/abcd-mproc-release4/unziped:/bids_input:ro -v /data5/open_data/ABCD/derivatives_2YFU:/output -v /users/hjd/freesurfer/license/license.txt:/opt/freesurfer/license.txt dcanumn/abcd-hcp-pipeline:v0.1.5 /bids_input /output --freesurfer-license=/opt/freesurfer/license.txt --ignore func
```

### What version of the abcd-hcp pipeline are you using?

v0.1.5

### Directory Structure

![image](https://github.com/user-attachments/assets/48178d71-9df2-4bad-a4f4-379f1a898912)

### Relevant log output

```shell
Traceback (most recent call last):
  File "/app/run.py", line 396, in <module>
    _cli()
  File "/app/run.py", line 69, in _cli
    return interface(**kwargs)
  File "/app/run.py", line 291, in interface
    session_spec = ParameterSettings(session, out_dir)
  File "/app/pipelines.py", line 106, in __init__
    self.bids_data['t1w_metadata'])
  File "/app/helpers.py", line 295, in get_realdwelltime
    pBW = metadata['PixelBandwidth']
KeyError: 'PixelBandwidth'
```

### Add any additional information or context about the problem here.

Tried docker image latest version and then v0.1.5, got the same issue

**Comment by LuciMoore** [comment]
@JD-Hwang apologies for the delay - can you please remove the subject and session IDs from the posted issue? I believe the central ABCD team instructed us not to include even the NDAR subject IDs outside of protected locations

I would use the flags `--participant-label` and `--session-id` to submit subjects/sessions for processing separately (this will make it easier to debug when individual sessions run into errors). Also you should only process subjects that have an anat folder: the default behavior is to process all IDs found in the BIDS input directory, so it probably errored out on the first subject (which only contains dwi data) and exited processing

**Comment by JD-Hwang** [comment]
@LuciMoore Thank you for your answers! I'm trying to preprocess subjects with anat folder. Also, I removed the subject and session IDs by deleting the images included. Thank you for letting me know!

**Comment by pollaro** [comment]
@LuciMoore I've gotten this, too. 
should probably be `pBW = metadata.get('PixelBandwidth', 1)`

1 as the default since it's the denominator

**Comment by LuciMoore** [comment]
@pollaro I think in this case the T1w data was just missing from the inputs because`PixelBandwidth` shouldn't be missing from ABCD T1w metadata. If that field is indeed missing for some reason (e.g. you're processing a different dataset), it would probably be best to update the metadata to include this field instead of having the pipeline use a default value. But let me know if you would like us to reopen this issue! @madisoth tagging you for awareness

**Comment by ReveRoyl** [comment]
@pollaro @JD-Hwang @LuciMoore 
Hi, I am using the  rsfmri and T1w data (anat and func) from ABCD minimally proprecessed data and encountered the same issue: KeyError: 'PixelBandwidth'
The T1W json file is like:
{"RepetitionTime": 0.00514, "EchoTime": 0.0020440000000000002, "FlipAngle": 8.0, "InversionTime": 1.06}
May I ask how did you finally solve this problem?

**Comment by LuciMoore** [comment]
@ReveRoyl I would suggest updating the sidecar jsons for the anatomical files to include PixelBandwidth! Let us know if you run into further issues

**Comment by ReveRoyl** [comment]
@LuciMoore Thank you for your reply! I am using the ABCD data: release 5.0 Minimally Processed Data All resting-state fMRI – June 2023. from: https://nda.nih.gov/general-query.html?q=query=featured-datasets:Adolescent%20Brain%20Cognitive%20Development%20Study%20(ABCD)

It seems that {"RepetitionTime": 0.00514, "EchoTime": 0.0020440000000000002, "FlipAngle": 8.0, "InversionTime": 1.06} is all the information included in the T1w sidecar jsons. 
It is the raw data. Thought 'PixelBandwidth' shouldn't be missing from ABCD T1w metadata, it does.
Is there anyway I can skip this process?
