### ISSUE TITLE
processing with phase/magnitude fmaps only

### ISSUE THREAD

**Issue by hough129** [DCAN-Labs/abcd-hcp-pipeline#32]
Errors I'm getting when I'm trying to run the pipeline with only 'magnitude1', 'magnitude2', 'phase1', and 'phase2' fieldmaps (I do not have epi fieldmaps I can use):
```
Traceback (most recent call last):
  File "/app/run.py", line 364, in <module>
    _cli()
  File "/app/run.py", line 67, in _cli
    return interface(**kwargs)
  File "/app/run.py", line 263, in interface
    session_spec = ParameterSettings(session, out_dir)
  File "/app/pipelines.py", line 147, in __init__
    types = self.bids_data['fmap'].keys()
AttributeError: 'list' object has no attribute 'keys'
```

**This was noted while debugging that might help (ignore if they is not helpful):**

`helpers.py line 189`: there needs to be cases added for magnitude/phase here

**Comment by madisoth** [comment]
A dataset I'm working on has magnitude1/magnitude2/phasediff (no phase1/phase2)-- if support for that combination can be added also, that would be a really huge help.

**Comment by hough129** [comment]
@madisoth phasediff is the difference between phase2 and phase1, right? Wouldn't that file have been created from phase1 and phase2 files to begin with? Or is phasediff acquired directly?

**Comment by madisoth** [comment]
I believe so, but this dataset doesn't include the original phase1/phase2, only phasediff.

**Comment by hough129** [comment]
@madisoth okay! @perronea and I have a time set up to look into adding phasediff capabilities in as well.
