### ISSUE TITLE
Exception: error caught during stage: FMRIVolume

### ISSUE THREAD

**Issue by fpichardo-umn** [DCAN-Labs/abcd-hcp-pipeline#90]
I got the error in the title while running the pipeline. It seemed to get through the FreeSurfer processing well, but it had an error during the resting-state fMRI processing. I'm unsure what the error is or what to do.

Below, I am including the relevant messages made by the pipeline and the structure of my dataset. I am running this with singularity.

=============================

**This is the last command to run:**
/opt/pipeline/fMRIVolume/GenericfMRIVolumeProcessingPipeline.sh \
    --path=/output/sub-001/ses-06/files \
    --subject=001 \
    --fmriname=ses-06_task-rest_run-01 \
    --fmritcs=/bids_input/sub-001/ses-06/func/sub-001_ses-06_task-rest_bold.nii.gz \
    --fmriscout=NONE \
    --SEPhaseNeg=/bids_input/sub-001/ses-06/fmap/sub-001_ses-06_acq-rest_dir-AP_epi.nii.gz \
    --SEPhasePos=/bids_input/sub-001/ses-06/fmap/sub-001_ses-06_acq-rest_dir-PA_epi.nii.gz \
    --fmapmag=NONE \
    --fmapphase=NONE \
    --fmapgeneralelectric=NONE \
    --echospacing=0.000659995 \
    --echodiff=NONE \
    --unwarpdir=y \
    --fmrires=2.0 \
    --dcmethod=TOPUP \
    --gdcoeffs=NONE \
    --topupconfig=/opt/pipeline/global/config/b02b0.cnf \
    --printcom= \
    --biascorrection=NONE \
    --mctype=MCFLIRT \
    --useT2=false

=============================

**Error message:**
Traceback (most recent call last):
  File "/app/run.py", line 397, in <module>
    _cli()
  File "/app/run.py", line 69, in _cli
    return interface(**kwargs)
  File "/app/run.py", line 393, in interface
    stage.run(ncpus)
  File "/app/pipelines.py", line 592, in run
    self.teardown(result)
  File "/app/pipelines.py", line 538, in teardown
    self.__class__.__name__)
Exception: error caught during stage: FMRIVolume

=============================

**Tail output from logs/FMRIVolume/ses-06_task-rest_run-01.out:**
 START: OneStepResampling
 
END: OneStepResampling
Tue Apr 18 14:47:28 CDT 2023 - GenericfMRIVolumeProcessingPipeline.sh - mkdir -p /output/sub-001/ses-06/files/MNINonLinear/Results/ses-06_task-rest_run-01
Tue Apr 18 14:48:06 CDT 2023 - GenericfMRIVolumeProcessingPipeline.sh - Intensity Normalization and Bias Removal
 
 START: IntensityNormalization
 
END: IntensityNormalization
Tue Apr 18 14:48:58 CDT 2023 - GenericfMRIVolumeProcessingPipeline.sh - Completed

=============================

However, the **logs/FMRIVolume/ses-06_task-rest_run-01.err** file was empty.

=============================

There was an error in the hariri task that did not break the processing, but we're uninterested in analyzing that data. This error occurred before the above relevant errors.

=============================

**The directory structure for my dataset:**
sub-001
sub-001/ses-06
sub-001/ses-06/anat
sub-001/ses-06/anat/sub-001_ses-06_T1w.json
sub-001/ses-06/anat/sub-001_ses-06_T1w.nii.gz
sub-001/ses-06/dwi
sub-001/ses-06/dwi/sub-001_ses-06_dir-PA_dwi.bval
sub-001/ses-06/dwi/sub-001_ses-06_dir-PA_dwi.json
sub-001/ses-06/dwi/sub-001_ses-06_dir-AP_dwi.bval
sub-001/ses-06/dwi/sub-001_ses-06_dir-AP_dwi.bvec
sub-001/ses-06/dwi/sub-001_ses-06_dir-AP_dwi.json
sub-001/ses-06/dwi/sub-001_ses-06_dir-PA_dwi.bvec
sub-001/ses-06/dwi/sub-001_ses-06_dir-PA_dwi.nii.gz
sub-001/ses-06/dwi/sub-001_ses-06_dir-AP_dwi.nii.gz
sub-001/ses-06/fmap
sub-001/ses-06/fmap/sub-001_ses-06_acq-rest_dir-AP_epi.json
sub-001/ses-06/fmap/sub-001_ses-06_acq-rest_dir-PA_epi.json
sub-001/ses-06/fmap/sub-001_ses-06_acq-hariri_dir-AP_epi.json
sub-001/ses-06/fmap/sub-001_ses-06_acq-hariri_dir-AP_epi.nii.gz
sub-001/ses-06/fmap/sub-001_ses-06_acq-rest_dir-AP_epi.nii.gz
sub-001/ses-06/fmap/sub-001_ses-06_acq-rest_dir-PA_epi.nii.gz
sub-001/ses-06/func
sub-001/ses-06/func/sub-001_ses-06_task-rest_bold.nii.gz
sub-001/ses-06/func/sub-001_ses-06_task-rest_bold.json
sub-001/ses-06/func/sub-001_ses-06_task-hariri_bold.nii.gz
sub-001/ses-06/func/sub-001_ses-06_task-hariri_bold.json
sub-001/ses-06/func/sub-001_ses-06_task-hariri_events.tsv
sub-001/ses-06/sub-001_ses-06_scans.json
sub-001/ses-06/sub-001_ses-06_scans.tsv

**Comment by fpichardo-umn** [comment]
I removed the hariri files and copied the other files to a different space with fewer permissions issues. The pipeline finished without issue on several participatns.
